"""Transcript cleanup — re-export shared backend engine."""

from __future__ import annotations

from backend.transcripts.cleanup import (  # noqa: F401
    CODE_BLOCK_RE,
    FILLER_RE,
    LLM_PREAMBLE_RE,
    MERMAID_RE,
    ORPHAN_SOURCE_LINE_RE,
    OUTER_FENCE_RE,
    SENTENCE_SPLIT_RE,
    STUTTER_RE,
    WHITESPACE_RE,
    aggressive_prefix_dedup,
    chunk_by_words,
    clean_transcript,
    count_code_blocks,
    count_mermaid_blocks,
    dedupe_h2_sections,
    dedupe_lines,
    dedupe_notes_tail,
    maximal_prefix_dedup,
    normalize_segment,
    postprocess_markdown,
    repair_all_fences,
    repair_mermaid_fences,
    repair_split_code_fences,
    sanitize_mermaid_blocks,
    split_sentences,
    strip_whole_response_wrapper,
    trim_incomplete_tail,
)

# Legacy alias used by older Studio copies
OUTER_FENCE_LINE_RE = OUTER_FENCE_RE

__all__ = [
    "CODE_BLOCK_RE",
    "FILLER_RE",
    "LLM_PREAMBLE_RE",
    "MERMAID_RE",
    "ORPHAN_SOURCE_LINE_RE",
    "OUTER_FENCE_LINE_RE",
    "OUTER_FENCE_RE",
    "SENTENCE_SPLIT_RE",
    "STUTTER_RE",
    "WHITESPACE_RE",
    "aggressive_prefix_dedup",
    "chunk_by_words",
    "clean_transcript",
    "count_code_blocks",
    "count_mermaid_blocks",
    "dedupe_h2_sections",
    "dedupe_lines",
    "dedupe_notes_tail",
    "maximal_prefix_dedup",
    "normalize_segment",
    "postprocess_markdown",
    "repair_all_fences",
    "repair_mermaid_fences",
    "repair_split_code_fences",
    "sanitize_mermaid_blocks",
    "split_sentences",
    "strip_whole_response_wrapper",
    "trim_incomplete_tail",
]
