// AUTO-GENERATED by scripts/build_extension_workers.ps1 - do not edit.
// Source parts: calt-gate-extension\gate_policy.js, calt-gate-extension\background.js

// ----- begin calt-gate-extension\gate_policy.js -----
/**
 * Shared distraction-gate helpers for Chromium + Firefox SelfTracker.
 * Edge-only SelfTracker gate policy (Chromium MV3).
 * Server `browser` payload is source of truth; seeds below are offline fallback.
 *
 * Keyword = URL + title; content_score.js adds weighted DOM text/link scoring.
 * Gate refresh ~4s when browsing; 1 min idle alarm backup.
 */
/* eslint-disable no-unused-vars */

var GATE_API_URL = "http://127.0.0.1:8000/api/behavior/distraction-gate";
var GATE_ALERT_URL = "http://127.0.0.1:8000/api/behavior/gate-alert";
var GATE_EXT_LOG_URL = "http://127.0.0.1:8000/api/behavior/gate-extension-log";
var CALT_TAB_CMD_URL = "http://127.0.0.1:8000/api/behavior/calt-tab-command";
var CALT_BIBLE_URL = "http://localhost:5173/bible";
var CALT_PRODUCTIVITY_URL = "http://localhost:5173/productivity?tab=plan";
var CALT_ORIGIN = "http://localhost:5173";
/** Suggested opportunistic gate refresh while tabs are active (seconds). */
var GATE_POLL_ACTIVE_S = 4;
/** Min gap between gate-alert POSTs (ms). */
var GATE_ALERT_GAP_MS = 45000;

/** Shopping / house / errands — allowed in free mode (and errands-lite). */
var FREE_LIFE_ALLOW_DOMAINS = [
  "amazon.com",
  "amazon.in",
  "flipkart.com",
  "myntra.com",
  "ajio.com",
  "bigbasket.com",
  "blinkit.com",
  "swiggy.com",
  "zomato.com",
  "ikea.com",
  "housing.com",
  "magicbricks.com",
  "nobroker.in",
  "99acres.com",
  "nykaa.com",
  "meesho.com",
];


/** @deprecated Prefer gateCache.browser.watch_domains — kept for GET_GATE / offline. */
var DISTRACTION_DOMAINS = [
  "netflix.com",
  "youtube.com",
  "youtu.be",
  "twitch.tv",
  "disneyplus.com",
  "primevideo.com",
  "hotstar.com",
  "instagram.com",
  "reddit.com",
  "x.com",
  "twitter.com",
  "tiktok.com",
  "facebook.com",
];

var FALLBACK_ALLOW_DOMAINS = [
  "localhost",
  "127.0.0.1",
  "colab.research.google.com",
  "scaler.com",
  "interviewbit.com",
  "scaleracademy.com",
  // Scaler lecture PDFs on S3 (also matched via isScalerAttachmentHost)
  "scaler-production-new.s3.ap-southeast-1.amazonaws.com",
  "github.com",
  "githubusercontent.com",
  "gitlab.com",
  "stackoverflow.com",
  "stackexchange.com",
  "docs.google.com",
  "drive.google.com",
  "drive.usercontent.google.com",
  "sheets.google.com",
  "slides.google.com",
  "meet.google.com",
  "classroom.google.com",
  "accounts.google.com",
  "myaccount.google.com",
  "gemini.google.com",
  "aistudio.google.com",
  "bard.google.com",
  "googleusercontent.com",
  // Omnibox / new-tab search hops — without these, typing scaler.com soft-lands
  // Bing/Google as "restricted" before the allowlisted destination loads.
  "google.com",
  "bing.com",
  "duckduckgo.com",
  "search.brave.com",
  "ntp.msn.com",
  "msn.com",
  "notion.so",
  "leetcode.com",
  "coursera.org",
  "udemy.com",
  "khanacademy.org",
  "arxiv.org",
  "wikipedia.org",
  "developer.mozilla.org",
  "python.org",
  "docs.python.org",
  "chatgpt.com",
  "claude.ai",
  "figma.com",
  // Data science / AI learning (keep in sync with browser_gate_policy.py)
  "numpy.org",
  "pandas.pydata.org",
  "scipy.org",
  "scikit-learn.org",
  "matplotlib.org",
  "seaborn.pydata.org",
  "plotly.com",
  "pytorch.org",
  "tensorflow.org",
  "keras.io",
  "huggingface.co",
  "jax.dev",
  "readthedocs.io",
  "polars.tech",
  "realpython.com",
  "pydata.org",
  "kaggle.com",
  "datacamp.com",
  "towardsdatascience.com",
  "medium.com",
  "fast.ai",
  "course.fast.ai",
  "deeplearning.ai",
  "paperswithcode.com",
  "distill.pub",
  "ocw.mit.edu",
  "cs231n.stanford.edu",
  "statisticsbyjim.com",
  "paperspace.com",
  "deepnote.com",
  "databricks.com",
  "stats.stackexchange.com",
  "datascience.stackexchange.com",
];

var FALLBACK_WATCH_DOMAINS = [
  "youtube.com",
  "youtu.be",
  "netflix.com",
  "primevideo.com",
  "hotstar.com",
  "disneyplus.com",
  "hulu.com",
  "twitch.tv",
  "crunchyroll.com",
];

/** Always blocked in bible / planning / study — even if server flags are stale. */
var FORCE_WATCH_HOSTS = [
  "youtube.com",
  "youtu.be",
  "netflix.com",
  "primevideo.com",
  "hotstar.com",
  "disneyplus.com",
  "hulu.com",
  "twitch.tv",
];
var STRICT_DAY_MODES = ["bible", "planning", "study"];

/**
 * Always blocked (distraction filter) — like FORCE_WATCH, but every mode including free.
 * Runs before enforce early-return so Disarmed / stale flags cannot open these.
 */
var FORCE_PORN_HOSTS = [
  "pornhub.com",
  "xvideos.com",
  "xnxx.com",
  "xhamster.com",
  "redtube.com",
  "youporn.com",
  "tube8.com",
  "spankbang.com",
  "chaturbate.com",
  "onlyfans.com",
  "porn.com",
  "sex.com",
  "nhentai.net",
  "rule34.xxx",
  "hentaihaven.xxx",
  "erome.com",
  "v3.erome.com",
  "eromecdn.com",
  "eporner.com",
  "hqporner.com",
  "porntrex.com",
  "beeg.com",
  "txxx.com",
  "redgifs.com",
  "imagefap.com",
  "motherless.com",
  "fapello.com",
  "missav.com",
  "jable.tv",
  "thisvid.com",
];
var FORCE_PORN_SUFFIXES = [".xxx", ".adult", ".porn", ".sex"];

var FALLBACK_PORN_DOMAINS = FORCE_PORN_HOSTS.slice();

var FALLBACK_PORN_SUFFIXES = FORCE_PORN_SUFFIXES.slice();

var FALLBACK_SOCIAL_DOMAINS = [
  "instagram.com",
  "reddit.com",
  "x.com",
  "twitter.com",
  "tiktok.com",
  "facebook.com",
];

/**
 * Temporary per-host soft-allow from locked.html (extension chrome.storage.local).
 * Short TTL on purpose — long windows get abused for YouTube.
 */
var TEMP_ALLOW_MS = 60000;
var TEMP_ALLOW_STORAGE_KEY = "tempAllows";

/** Offline keyword seed — prefer server block_keywords_list. Avoid bare "ass"/"sex". */
var FALLBACK_BLOCK_KEYWORDS = [
  "bdsm",
  "porn",
  "porno",
  "pornography",
  "xxx",
  "onlyfans",
  "fansly",
  "hentai",
  "nsfw",
  "nude",
  "nudes",
  "nudity",
  "fetish",
  "bondage",
  "blowjob",
  "handjob",
  "cumshot",
  "gangbang",
  "threesome",
  "milf",
  "incest",
  "rule34",
  "rule 34",
  "xhamster",
  "xvideos",
  "pornhub",
  "chaturbate",
  "redgifs",
  "hqporner",
  "eporner",
  "erome",
  "camgirl",
  "sex cam",
  "sex tape",
  "sex video",
  "adult video",
  "erotic",
  "erotica",
  "hardcore porn",
];

/** Weighted page-text score — keep in sync with backend/behavior/content_score.py */
var CONTENT_SCORE_WEIGHTS = {
  pornography: 4,
  "hardcore porn": 5,
  porn: 4,
  porno: 4,
  "xxx video": 5,
  xxx: 3,
  nsfw: 2,
  hentai: 4,
  onlyfans: 4,
  fansly: 3,
  chaturbate: 4,
  blowjob: 5,
  handjob: 5,
  cumshot: 5,
  creampie: 5,
  gangbang: 5,
  threesome: 4,
  deepthroat: 5,
  bdsm: 3,
  bondage: 3,
  fetish: 2,
  pegging: 4,
  milf: 3,
  incest: 5,
  rule34: 4,
  "rule 34": 4,
  "nude pics": 4,
  "nude photo": 4,
  nudes: 3,
  nudity: 2,
  nude: 2,
  "naked pics": 4,
  "naked photo": 4,
  erotic: 2,
  erotica: 2,
  "live sex": 5,
  "sex cam": 5,
  "sex tape": 5,
  "sex video": 4,
  "adult video": 3,
  camgirl: 4,
  "cam girl": 4,
  erome: 4,
  eporner: 4,
  redgifs: 4,
  pornhub: 4,
  xvideos: 4,
  xhamster: 4,
};

var CONTENT_SCORE_THRESHOLDS = {
  free: { warn: 8, lock: 16, maxSamples: 5 },
  study: { warn: 5, lock: 10, maxSamples: 3 },
};

function scorePageHaystack(text, weights, perTermCap) {
  var hay = String(text || "").toLowerCase();
  var wmap = weights || CONTENT_SCORE_WEIGHTS;
  var cap = typeof perTermCap === "number" ? perTermCap : 3;
  var terms = Object.keys(wmap).sort(function (a, b) {
    return b.length - a.length;
  });
  var score = 0;
  var matched = [];
  for (var i = 0; i < terms.length; i++) {
    var term = terms[i];
    var weight = Number(wmap[term]) || 0;
    if (weight <= 0 || term.length < 3) continue;
    var escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    var re = new RegExp("(^|[^a-z0-9])" + escaped + "([^a-z0-9]|$)", "gi");
    var hits = 0;
    var m;
    while ((m = re.exec(hay)) !== null) {
      hits++;
      if (m.index === re.lastIndex) re.lastIndex++;
    }
    if (hits <= 0) continue;
    var use = Math.min(hits, cap);
    score += weight * use;
    matched.push(term);
    hay = hay.replace(new RegExp("(^|[^a-z0-9])" + escaped + "([^a-z0-9]|$)", "gi"), "$1 $2");
  }
  return { score: score, matched: matched };
}

function decideContentScoreAction(opts) {
  opts = opts || {};
  var mode = String(opts.mode || "free").toLowerCase() === "study" ? "study" : "free";
  var th = CONTENT_SCORE_THRESHOLDS[mode];
  var score = Number(opts.score) || 0;
  var prev = Number(opts.prevScore) || 0;
  var idx = Number(opts.sampleIndex) || 0;
  var warned = Boolean(opts.warned);
  if (score >= th.lock) return "lock";
  if (score >= th.warn) {
    if (warned && score > prev) return "lock";
    if (!warned) return "warn";
  }
  if (idx >= 1 && score < th.warn && Math.abs(score - prev) <= 1) return "stop";
  if (idx + 1 >= th.maxSamples) return "stop";
  return "continue";
}

function hostnameFromUrl(url) {
  try {
    return new URL(url).hostname.toLowerCase().replace(/^www\./, "");
  } catch (e) {
    return "";
  }
}

function hostMatchesDomain(host, domain) {
  var h = String(host || "")
    .toLowerCase()
    .replace(/^www\./, "");
  var d = String(domain || "")
    .toLowerCase()
    .replace(/^www\./, "");
  if (!h || !d) return false;
  return h === d || h.endsWith("." + d);
}

/** Scaler lecture attachment buckets on S3 — not all of amazonaws.com. */
function isScalerAttachmentHost(host) {
  var h = String(host || "")
    .toLowerCase()
    .replace(/^www\./, "");
  if (!h.endsWith(".amazonaws.com")) return false;
  if (h.indexOf(".s3.") < 0) return false;
  var bucket = h.split(".")[0] || "";
  return bucket.indexOf("scaler") === 0;
}

function listMatch(host, domains) {
  if (!domains || !domains.length) return false;
  for (var i = 0; i < domains.length; i++) {
    if (hostMatchesDomain(host, domains[i])) return true;
  }
  return false;
}

function isStrictDayMode(mode) {
  return STRICT_DAY_MODES.indexOf(String(mode || "").toLowerCase()) >= 0;
}

function isForceWatchHost(host) {
  return listMatch(host, FORCE_WATCH_HOSTS);
}

function isForcePornHost(host) {
  var h = String(host || "")
    .toLowerCase()
    .replace(/^www\./, "");
  if (!h) return false;
  if (listMatch(h, FORCE_PORN_HOSTS)) return true;
  for (var i = 0; i < FORCE_PORN_SUFFIXES.length; i++) {
    if (h.endsWith(FORCE_PORN_SUFFIXES[i])) return true;
  }
  return false;
}

function normalizeHost(host) {
  return String(host || "")
    .toLowerCase()
    .replace(/^www\./, "");
}

/**
 * Watch / porn / social (and force lists) must never receive a temp allow.
 * @returns {boolean}
 */
function isTempAllowExcludedHost(host, policy) {
  var h = normalizeHost(host);
  if (!h) return true;
  if (isForceWatchHost(h) || isForcePornHost(h)) return true;
  var pol = policy || browserPolicyOrFallback(null);
  var cat = classifyHostCategory(h, pol);
  return cat === "watch" || cat === "porn" || cat === "social";
}

/** Drop expired entries; keep { host, until } shape. */
function pruneTempAllows(list, now) {
  var t = typeof now === "number" ? now : Date.now();
  var out = [];
  if (!list || !list.length) return out;
  for (var i = 0; i < list.length; i++) {
    var e = list[i];
    if (!e || !e.host) continue;
    var until = Number(e.until);
    if (!until || until <= t) continue;
    out.push({ host: normalizeHost(e.host), until: until });
  }
  return out;
}

/**
 * @returns {boolean} true if host has a non-expired temp allow and is not excluded.
 */
function isHostTempAllowed(host, tempAllows, now, policy) {
  var h = normalizeHost(host);
  if (!h) return false;
  if (isTempAllowExcludedHost(h, policy)) return false;
  var t = typeof now === "number" ? now : Date.now();
  var list = pruneTempAllows(tempAllows, t);
  for (var i = 0; i < list.length; i++) {
    if (hostMatchesDomain(h, list[i].host) || hostMatchesDomain(list[i].host, h)) {
      if (t < list[i].until) return true;
    }
  }
  return false;
}

function tempAllowUntilForHost(host, tempAllows, now) {
  var h = normalizeHost(host);
  if (!h) return 0;
  var t = typeof now === "number" ? now : Date.now();
  var list = pruneTempAllows(tempAllows, t);
  var best = 0;
  for (var i = 0; i < list.length; i++) {
    if (hostMatchesDomain(h, list[i].host) || hostMatchesDomain(list[i].host, h)) {
      if (list[i].until > best) best = list[i].until;
    }
  }
  return best > t ? best : 0;
}

/**
 * Decide whether locked.html may grant a temp allow for this host.
 * @returns {{ ok: boolean, error?: string, entry?: { host: string, until: number } }}
 */
function buildTempAllowGrant(host, now, policy) {
  var h = normalizeHost(host);
  var t = typeof now === "number" ? now : Date.now();
  var pol = policy || browserPolicyOrFallback(null);
  if (!h) return { ok: false, error: "No host to allow" };
  if (isTempAllowExcludedHost(h, pol)) {
    var cat = classifyHostCategory(h, pol);
    if (isForceWatchHost(h) || cat === "watch") {
      return { ok: false, error: "Watch sites can't be temporarily allowed" };
    }
    if (isForcePornHost(h) || cat === "porn") {
      return { ok: false, error: "Distractions can't be temporarily allowed" };
    }
    if (cat === "social") {
      return { ok: false, error: "Social sites can't be temporarily allowed" };
    }
    return { ok: false, error: "This site can't be temporarily allowed" };
  }
  return { ok: true, entry: { host: h, until: t + TEMP_ALLOW_MS } };
}

/** Upsert one grant into the list (prunes expired). */
function upsertTempAllow(list, entry, now) {
  var t = typeof now === "number" ? now : Date.now();
  var out = pruneTempAllows(list, t);
  if (!entry || !entry.host) return out;
  var h = normalizeHost(entry.host);
  var until = Number(entry.until) || 0;
  if (!h || until <= t) return out;
  var next = [];
  for (var i = 0; i < out.length; i++) {
    if (out[i].host !== h) next.push(out[i]);
  }
  next.push({ host: h, until: until });
  return next;
}

function decodeUriSafe(s) {
  try {
    return decodeURIComponent(String(s || ""));
  } catch (e) {
    return String(s || "");
  }
}

/**
 * Boundary-aware keyword match (case-insensitive). Returns matched keyword or "".
 */
function textMatchesKeywords(haystack, keywords) {
  var hay = decodeUriSafe(haystack).toLowerCase();
  if (!hay || !keywords || !keywords.length) return "";
  for (var i = 0; i < keywords.length; i++) {
    var kw = String(keywords[i] || "")
      .trim()
      .toLowerCase();
    if (!kw || kw.length < 3) continue;
    var escaped = kw.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    var re = new RegExp("(^|[^a-z0-9])" + escaped + "([^a-z0-9]|$)", "i");
    if (re.test(hay)) return kw;
  }
  return "";
}

function browserPolicyOrFallback(browser) {
  var b = browser || {};
  var mode = String(b.mode || "").toLowerCase();
  if (["bible", "planning", "study", "free"].indexOf(mode) < 0) {
    // Prefer study (watch blocked) over free when mode missing but flags look enforcing.
    mode = b.enforce || b.block_other || b.block_watch_sites ? "study" : "free";
  }
  var strict = isStrictDayMode(mode);
  return {
    mode: mode,
    mode_label: b.mode_label || mode.toUpperCase(),
    allow_domains: b.allow_domains && b.allow_domains.length ? b.allow_domains : FALLBACK_ALLOW_DOMAINS,
    watch_domains: b.watch_domains && b.watch_domains.length ? b.watch_domains : FALLBACK_WATCH_DOMAINS,
    porn_domains: b.porn_domains && b.porn_domains.length ? b.porn_domains : FALLBACK_PORN_DOMAINS,
    porn_suffixes: b.porn_suffixes && b.porn_suffixes.length ? b.porn_suffixes : FALLBACK_PORN_SUFFIXES,
    social_domains: b.social_domains && b.social_domains.length ? b.social_domains : FALLBACK_SOCIAL_DOMAINS,
    block_keywords_list:
      b.block_keywords_list && b.block_keywords_list.length
        ? b.block_keywords_list
        : FALLBACK_BLOCK_KEYWORDS,
    localhost_path_prefixes:
      b.localhost_path_prefixes && b.localhost_path_prefixes.length
        ? b.localhost_path_prefixes
        : ["/bible", "/productivity", "/profile", "/lecture-notes"],
    // Strict day modes always block watch (YouTube etc.) — never trust a stale false flag.
    block_watch_sites: b.block_watch_sites === true || strict,
    block_porn: b.block_porn !== false,
    block_social: b.block_social === true || strict,
    block_keywords: b.block_keywords !== false,
    block_other: b.block_other === true || strict,
    strict_allowlist: b.strict_allowlist === true || mode === "bible" || mode === "planning",
    enforce: Boolean(b.enforce) || strict,
    redirect_url: b.redirect_url || null,
    redirect_reason: b.redirect_reason || null,
    bible_url: b.bible_url || CALT_BIBLE_URL,
    plan_url: b.plan_url || CALT_PRODUCTIVITY_URL,
    morning_next: b.morning_next || "open",
    allow_free_life: b.allow_free_life === true,
    free_life_allow_domains:
      b.free_life_allow_domains && b.free_life_allow_domains.length
        ? b.free_life_allow_domains
        : FREE_LIFE_ALLOW_DOMAINS,
  };
}

/**
 * Classify host: allow wins over porn/watch/social.
 * @returns {"allow"|"porn"|"watch"|"social"|"other"}
 */
function classifyHostCategory(host, policy) {
  var h = String(host || "")
    .toLowerCase()
    .replace(/^www\./, "");
  if (!h) return "other";
  if (
    h === "localhost" ||
    h === "127.0.0.1" ||
    listMatch(h, policy.allow_domains) ||
    isScalerAttachmentHost(h)
  ) {
    return "allow";
  }
  // Free / errands-lite: shopping & house sites allowed (study blocks unless allow_free_life)
  var freeLife =
    policy.mode === "free" ||
    policy.allow_free_life === true ||
    (policy.mode || "") === "errands";
  var lifeList =
    policy.free_life_allow_domains && policy.free_life_allow_domains.length
      ? policy.free_life_allow_domains
      : FREE_LIFE_ALLOW_DOMAINS || [];
  if (freeLife && listMatch(h, lifeList)) {
    return "allow";
  }
  if (listMatch(h, policy.porn_domains)) return "porn";
  var suffixes = policy.porn_suffixes || [];
  for (var i = 0; i < suffixes.length; i++) {
    if (h.endsWith(suffixes[i])) return "porn";
  }
  if (listMatch(h, policy.watch_domains)) return "watch";
  if (listMatch(h, policy.social_domains)) return "social";
  return "other";
}

/** Legacy helper — watch/social seed only (no allow/porn). Prefer shouldBlockUrl. */
function isDistractionUrl(url) {
  if (!url || typeof url !== "string") return false;
  var host = hostnameFromUrl(url);
  if (!host) return false;
  var policy = browserPolicyOrFallback(null);
  var cat = classifyHostCategory(host, policy);
  return cat === "watch" || cat === "social";
}

/**
 * Whether extension should redirect this tab URL given cached gate.
 * Allowlist never redirects (strict modes also require localhost SPA paths).
 * Porn/watch/social/keywords/other respect server flags + browser.mode.
 * Keywords: URL path/query + optional page title only (no DOM scraping).
 * @returns {boolean}
 */
/** FREE / goal met / earned reward day — YouTube+games open; porn/keywords still blocked. */
function isFreeDay(gateCache) {
  if (!gateCache) return false;
  var browser = browserPolicyOrFallback(gateCache.browser);
  return (
    browser.mode === "free" ||
    Boolean(gateCache.day_unlimited) ||
    Boolean(gateCache.reward_day) ||
    Boolean(gateCache.unlocked && !isStrictDayMode(browser.mode))
  );
}

function shouldBlockUrl(url, gateCache, title) {
  if (!url || typeof url !== "string") return false;
  // ok=true for live gate; degraded/stale still enforces last known strict mode (fail-closed).
  if (!gateCache || (!gateCache.ok && !gateCache.degraded)) return false;
  var browser = browserPolicyOrFallback(gateCache.browser);
  var host = hostnameFromUrl(url);
  if (!host) return false;

  var cat = classifyHostCategory(host, browser);
  var freeDay = isFreeDay(gateCache);

  // Distraction filter always on (before enforce) — stale Disarmed cannot open those TLDs/domains.
  if (isForcePornHost(host) || cat === "porn") return true;
  // Keywords on non-allow hosts always (allowlist still wins — e.g. Colab notebook ids).
  if (cat !== "allow" && browser.block_keywords !== false) {
    var adultHit = textMatchesKeywords(
      url + " " + (title || ""),
      browser.block_keywords_list
    );
    if (adultHit) return true;
  }

  // FREE / goal met / reward day: never softLand YouTube/social/other — distractions above.
  if (freeDay) return false;

  var enforce =
    Boolean(browser.enforce) ||
    Boolean(gateCache.enforce) ||
    Boolean(gateCache.locked) ||
    Boolean(gateCache.degraded && isStrictDayMode(browser.mode));
  if (!enforce) return false;

  // Hard force: youtube.com / youtu.be never allowed in bible / planning / study.
  if (isForceWatchHost(host) && isStrictDayMode(browser.mode)) return true;

  // Per-host temp allow (locked.html "Allow this site 60 sec") — never watch/porn/social.
  var tempAllows = gateCache.temp_allows || gateCache.tempAllows || [];
  if (isHostTempAllowed(host, tempAllows, Date.now(), browser)) {
    return false;
  }

  if (cat === "allow") {
    if (browser.strict_allowlist && (host === "localhost" || host === "127.0.0.1")) {
      if (!isCaltSpaUrl(url)) return true;
    }
    return false;
  }
  if (cat === "watch" && browser.block_watch_sites) return true;
  if (cat === "social" && browser.block_social) return true;
  if (browser.block_other) return true;
  return false;
}

/** Category for voice alert when blocking (best-effort). */
function blockKindForUrl(url, gateCache, title) {
  var browser = browserPolicyOrFallback(gateCache && gateCache.browser);
  var morning = (gateCache && gateCache.morning) || {};
  var next = browser.morning_next || morning.next || "open";
  var mode = browser.mode || "free";
  if (next === "bible" || mode === "bible") return "morning_bible_required";
  if (next === "plan" || mode === "planning") return "morning_plan_required";
  var host = hostnameFromUrl(url);
  var cat = classifyHostCategory(host, browser);
  if (cat === "porn") return "porn_or_keyword_block";
  if (cat === "watch" || cat === "social") return "watch_site_block";
  if (browser.block_keywords) {
    var hit = textMatchesKeywords(url + " " + (title || ""), browser.block_keywords_list);
    if (hit) return "porn_or_keyword_block";
  }
  if (mode === "study") return "generic_rule_break";
  return "generic_rule_break";
}

/**
 * Soft-landing: morning bible/plan SPA, else extension locked.html.
 */
function redirectTargetUrl(gateCache, lockedPageUrl) {
  var browser = browserPolicyOrFallback(gateCache && gateCache.browser);
  var morning = (gateCache && gateCache.morning) || {};
  var next = browser.morning_next || morning.next || "open";
  var mode = browser.mode || "free";
  if (next === "bible" || mode === "bible") {
    return browser.bible_url || morning.bible_url || CALT_BIBLE_URL;
  }
  if (next === "plan" || mode === "planning") {
    return browser.plan_url || morning.plan_url || CALT_PRODUCTIVITY_URL;
  }
  if (browser.redirect_url) return browser.redirect_url;
  return lockedPageUrl;
}

function isExtensionOrInternalUrl(url) {
  if (!url) return true;
  return (
    url.startsWith("chrome://") ||
    url.startsWith("chrome-extension://") ||
    url.startsWith("edge://") ||
    url.startsWith("about:") ||
    url.startsWith("moz-extension://") ||
    url.startsWith("devtools://")
  );
}

function isCaltSpaUrl(url) {
  // Any local CALT origin — gate soft-land skips; SelfTracker owns internet tabs only.
  if (!url) return false;
  try {
    var u = new URL(url);
    var host = u.hostname.toLowerCase();
    return host === "localhost" || host === "127.0.0.1";
  } catch (e) {
    return false;
  }
}

// ----- end calt-gate-extension\gate_policy.js -----

// ----- begin calt-gate-extension\background.js -----
// ============================================================
// CALT Gate — blocker only (MV3 DNR + light softLand)
// No telemetry / WebSocket. Pair with CALT SelfTracker.
// Watch hosts = DNR only. Other blocks = one-tab softLand.
// ============================================================

/* global GATE_API_URL, GATE_ALERT_URL, GATE_EXT_LOG_URL, GATE_ALERT_GAP_MS, FORCE_WATCH_HOSTS,
   FORCE_PORN_HOSTS, isStrictDayMode, TEMP_ALLOW_STORAGE_KEY, TEMP_ALLOW_MS, pruneTempAllows,
   buildTempAllowGrant, upsertTempAllow, isTempAllowExcludedHost,
   tempAllowUntilForHost, browserPolicyOrFallback, shouldBlockUrl,
   redirectTargetUrl, isCaltSpaUrl, blockKindForUrl, hostnameFromUrl,
   isForceWatchHost, isForcePornHost, classifyHostCategory, isExtensionOrInternalUrl,
   CALT_BIBLE_URL, CALT_PRODUCTIVITY_URL */

// Shared helpers are prepended by scripts/build_extension_workers.ps1 into service_worker.js

var DNR_WATCH_RULE_BASE = 9200;
var MAX_DNR_WATCH_HOSTS = 8;
/** Hard-block distraction hosts in every mode (including FREE). */
var DNR_PORN_RULE_BASE = 9300;
var MAX_DNR_PORN_HOSTS = 40;
var GATE_POLL_MS = 12000;
var SOFTLAND_DEDUP_MS = 15000;

var extAPI = typeof chrome !== "undefined" && chrome.runtime ? chrome : browser;

var gateCache = null;
var redirectsEnabled = true;
var lastGateFetchAt = 0;
var lastDnrFingerprint = "";
var lastDnrPornFingerprint = "";
var gatePollTimer = null;
var lastAlertAt = 0;
var softLandDone = Object.create(null);
var softLandInFlight = Object.create(null);
var tempAllowsCache = [];
var lastGateModeKey = "";
var softLandRecentAt = [];
var SOFTLAND_STORM_WINDOW_MS = 8000;
var SOFTLAND_STORM_MAX = 6;
var REDIRECT_COOLDOWN_MS = 30000;
var redirectCooldownUntil = 0;
var lastNotifyAt = 0;
var NOTIFY_GAP_MS = 8000;

extAPI.storage.local.get(["gateCache", "redirectsEnabled", "tempAllows"], function (result) {
  if (result.gateCache) gateCache = result.gateCache;
  if (typeof result.redirectsEnabled === "boolean") redirectsEnabled = result.redirectsEnabled;
  if (Array.isArray(result.tempAllows)) {
    tempAllowsCache =
      typeof pruneTempAllows === "function" ? pruneTempAllows(result.tempAllows, Date.now()) : result.tempAllows;
  }
});

function lockedPageUrl() {
  return extAPI.runtime.getURL("locked.html");
}

function lockedPageUrlForBlocked(blockedUrl) {
  var base = lockedPageUrl();
  var host = "";
  try {
    host = typeof hostnameFromUrl === "function" ? hostnameFromUrl(blockedUrl) : "";
  } catch (e) {
    host = "";
  }
  if (!host) return base;
  var q = "host=" + encodeURIComponent(host);
  try {
    if (blockedUrl && String(blockedUrl).indexOf("http") === 0) {
      q += "&from=" + encodeURIComponent(String(blockedUrl).slice(0, 500));
    }
  } catch (e2) {
    /* ignore */
  }
  return base + "?" + q;
}

function gateCacheForBlockCheck() {
  if (!gateCache) return null;
  return Object.assign({}, gateCache, { temp_allows: tempAllowsCache, tempAllows: tempAllowsCache });
}

function reportGateAlert(kind, detail) {
  var now = Date.now();
  if (now - lastAlertAt < (GATE_ALERT_GAP_MS || 45000)) return;
  lastAlertAt = now;
  try {
    fetch(GATE_ALERT_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ kind: kind || "generic_rule_break", detail: detail || "" }),
      cache: "no-store",
    }).catch(function () {});
  } catch (e) {
    /* ignore */
  }
}

function logExtensionEvent(event, payload) {
  var url = typeof GATE_EXT_LOG_URL !== "undefined" ? GATE_EXT_LOG_URL : "";
  if (!url) return;
  try {
    fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(
        Object.assign({ event: event || "unknown", source: "calt-gate" }, payload || {})
      ),
      cache: "no-store",
    }).catch(function () {});
  } catch (e) {
    /* ignore */
  }
}

function redirectsPausedByCircuit() {
  return redirectCooldownUntil && Date.now() < redirectCooldownUntil;
}

function noteSoftLandAttempt() {
  var now = Date.now();
  softLandRecentAt.push(now);
  while (softLandRecentAt.length && now - softLandRecentAt[0] > SOFTLAND_STORM_WINDOW_MS) {
    softLandRecentAt.shift();
  }
  if (softLandRecentAt.length >= SOFTLAND_STORM_MAX) {
    redirectCooldownUntil = now + REDIRECT_COOLDOWN_MS;
    softLandRecentAt = [];
    logExtensionEvent("circuit_breaker", {
      detail: "softLand storm — redirects paused " + Math.round(REDIRECT_COOLDOWN_MS / 1000) + "s",
      notify: false,
    });
    console.warn("CALT Gate: softLand circuit breaker — redirects paused");
    return true;
  }
  return false;
}

function showBlockNotification(title, message) {
  var now = Date.now();
  if (now - lastNotifyAt < NOTIFY_GAP_MS) return;
  lastNotifyAt = now;
  if (!extAPI.notifications || !extAPI.notifications.create) return;
  try {
    extAPI.notifications.create("calt-gate-" + now, {
      type: "basic",
      iconUrl: "icon.png",
      title: title || "CALT Gate",
      message: message || "One tab redirected — Edge was not closed.",
      priority: 1,
    });
  } catch (e) {
    /* ignore */
  }
}

function watchBlockActive() {
  if (!redirectsEnabled) return false;
  if (!gateCache || (!gateCache.ok && !gateCache.degraded)) return false;
  // Reward day / goal unlock must clear YouTube DNR (softLand alone is not enough).
  if (typeof isFreeDay === "function" && isFreeDay(gateCache)) return false;
  var browser = gateCache.browser || {};
  var mode = String(browser.mode || "").toLowerCase();
  if (mode === "free" || gateCache.day_unlimited || gateCache.reward_day || gateCache.unlocked) {
    return false;
  }
  if (browser.block_watch_sites) return true;
  return typeof isStrictDayMode === "function" && isStrictDayMode(mode);
}

async function syncDeclarativeWatchBlock(opts) {
  opts = opts || {};
  if (!extAPI.declarativeNetRequest || !extAPI.declarativeNetRequest.updateDynamicRules) {
    return;
  }
  var raw = typeof FORCE_WATCH_HOSTS !== "undefined" ? FORCE_WATCH_HOSTS : ["youtube.com", "youtu.be"];
  var hosts = raw.slice(0, MAX_DNR_WATCH_HOSTS);
  var active = watchBlockActive();
  var fingerprint = (active ? "1" : "0") + "|" + hosts.join(",");
  if (!opts.force && fingerprint === lastDnrFingerprint) return;

  var removeIds = [];
  for (var i = 0; i < MAX_DNR_WATCH_HOSTS + 4; i++) removeIds.push(DNR_WATCH_RULE_BASE + i);

  try {
    if (!active) {
      await extAPI.declarativeNetRequest.updateDynamicRules({
        removeRuleIds: removeIds,
        addRules: [],
      });
      lastDnrFingerprint = fingerprint;
      return;
    }
    var target = lockedPageUrl();
    var addRules = [];
    for (var j = 0; j < hosts.length; j++) {
      addRules.push({
        id: DNR_WATCH_RULE_BASE + j,
        priority: 100,
        action: { type: "redirect", redirect: { url: target } },
        condition: {
          requestDomains: [hosts[j]],
          resourceTypes: ["main_frame"],
        },
      });
    }
    await extAPI.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: removeIds,
      addRules: addRules,
    });
    lastDnrFingerprint = fingerprint;
  } catch (e) {
    console.warn("CALT Gate: DNR watch sync failed", e);
  }
}

/** Always-on DNR for distraction hosts (FREE + study). SoftLand is backup only. */
async function syncDeclarativePornBlock(opts) {
  opts = opts || {};
  if (!extAPI.declarativeNetRequest || !extAPI.declarativeNetRequest.updateDynamicRules) {
    return;
  }
  var raw =
    typeof FORCE_PORN_HOSTS !== "undefined" && FORCE_PORN_HOSTS.length
      ? FORCE_PORN_HOSTS
      : ["pornhub.com", "xvideos.com", "erome.com"];
  var hosts = raw.slice(0, MAX_DNR_PORN_HOSTS);
  var active = redirectsEnabled !== false;
  var fingerprint = (active ? "1" : "0") + "|porn|" + hosts.join(",");
  if (!opts.force && fingerprint === lastDnrPornFingerprint) return;

  var removeIds = [];
  for (var i = 0; i < MAX_DNR_PORN_HOSTS + 4; i++) removeIds.push(DNR_PORN_RULE_BASE + i);

  try {
    if (!active) {
      await extAPI.declarativeNetRequest.updateDynamicRules({
        removeRuleIds: removeIds,
        addRules: [],
      });
      lastDnrPornFingerprint = fingerprint;
      return;
    }
    var target = lockedPageUrl();
    var addRules = [];
    for (var j = 0; j < hosts.length; j++) {
      addRules.push({
        id: DNR_PORN_RULE_BASE + j,
        priority: 110,
        action: { type: "redirect", redirect: { url: target } },
        condition: {
          requestDomains: [hosts[j]],
          resourceTypes: ["main_frame"],
        },
      });
    }
    await extAPI.declarativeNetRequest.updateDynamicRules({
      removeRuleIds: removeIds,
      addRules: addRules,
    });
    lastDnrPornFingerprint = fingerprint;
  } catch (e) {
    console.warn("CALT Gate: DNR distraction sync failed", e);
  }
}

function caltExtensionHeaders() {
  var mode = "";
  try {
    mode = String((gateCache && gateCache.browser && gateCache.browser.mode) || "");
  } catch (e) {
    mode = "";
  }
  var paused = false;
  try {
    paused = typeof redirectsPausedByCircuit === "function" && redirectsPausedByCircuit();
  } catch (e2) {
    paused = false;
  }
  return {
    "X-CALT-Extension": "calt-gate",
    "X-CALT-Ext-Mode": mode,
    "X-CALT-Ext-Circuit": paused ? "1" : "0",
    "X-CALT-Ext-Paused": redirectsEnabled === false ? "1" : "0",
  };
}

async function pollGate() {
  var now = Date.now();
  if (lastGateFetchAt && now - lastGateFetchAt < GATE_POLL_MS - 500) return;
  try {
    var r = await fetch(GATE_API_URL, { cache: "no-store", headers: caltExtensionHeaders() });
    if (!r.ok) throw new Error("HTTP " + r.status);
    var g = await r.json();
    lastGateFetchAt = Date.now();
    var morning = g.morning || {};
    var browser = g.browser || {};
    gateCache = {
      ok: true,
      stale: false,
      degraded: false,
      fetched_at: lastGateFetchAt,
      locked: Boolean(g.locked),
      unlocked: Boolean(g.unlocked),
      enabled: Boolean(g.enabled),
      remaining_minutes: g.remaining_minutes ?? null,
      chapter_goal_met: Boolean(g.chapter_goal_met),
      day_unlimited: Boolean(g.day_unlimited),
      day_pass: Boolean(g.day_pass),
      reward_day: Boolean(g.reward_day),
      productive_minutes: g.productive_minutes ?? 0,
      daily_goal_minutes: g.daily_goal_minutes ?? 0,
      suggested_links: Array.isArray(g.suggested_links) ? g.suggested_links : [],
      current_block: g.current_block || null,
      morning: {
        next: morning.next || "open",
        bible_done: Boolean(morning.bible_done),
        plan_done: Boolean(morning.plan_done),
        bible_url: morning.bible_url || null,
        plan_url: morning.plan_url || null,
        redirect_url: morning.redirect_url || null,
        hint: morning.hint || "",
      },
      browser: browser,
      enforce: Boolean(browser.enforce) || Boolean(g.locked),
    };
    await extAPI.storage.local.set({ gateCache: gateCache });
    var modeNow = String(browser.mode || "").toLowerCase();
    var freeNow =
      Boolean(g.day_unlimited) || Boolean(g.reward_day) || modeNow === "free";
    var modeKey =
      modeNow +
      "|" +
      (freeNow ? "1" : "0") +
      "|" +
      Boolean(browser.block_watch_sites) +
      "|" +
      Boolean(g.locked);
    var forceDnr = modeKey !== lastGateModeKey;
    if (forceDnr) lastGateModeKey = modeKey;
    await syncDeclarativeWatchBlock({ force: forceDnr });
    await syncDeclarativePornBlock({ force: forceDnr });
  } catch (e) {
    var err = String(e && e.message ? e.message : e);
    var prev = gateCache && typeof gateCache === "object" ? gateCache : null;
    var prevBrowser = (prev && prev.browser) || {};
    var prevMode = String(prevBrowser.mode || "").toLowerCase();
    var prevFree =
      prevMode === "free" ||
      Boolean(prev && (prev.day_unlimited || prev.reward_day || prev.unlocked));
    if (prev && (prev.ok || prev.degraded)) {
      gateCache = Object.assign({}, prev, {
        ok: true,
        stale: true,
        degraded: true,
        fetched_at: Date.now(),
        error: err,
        day_unlimited: Boolean(prev.day_unlimited) || prevFree,
        reward_day: Boolean(prev.reward_day),
        unlocked: Boolean(prev.unlocked) || prevFree,
        browser: Object.assign({}, prevBrowser, {
          block_watch_sites: prevFree ? false : true,
          block_social: prevFree ? false : prevBrowser.block_social === true,
          block_other: prevFree ? false : true,
          block_porn: prevBrowser.block_porn !== false,
          mode: prevFree ? "free" : prevMode || "study",
          mode_label: prevFree ? "FREE" : prevBrowser.mode_label || "STUDY",
          enforce: true,
        }),
      });
    } else {
      gateCache = {
        ok: true,
        stale: true,
        degraded: true,
        fetched_at: Date.now(),
        locked: true,
        unlocked: false,
        enabled: true,
        enforce: true,
        error: err,
        morning: { next: "open", bible_done: false, plan_done: false },
        browser: {
          mode: "study",
          mode_label: "STUDY",
          enforce: true,
          block_watch_sites: true,
          block_social: true,
          block_other: true,
          block_porn: true,
          block_keywords: true,
        },
      };
    }
    await extAPI.storage.local.set({ gateCache: gateCache });
    await syncDeclarativeWatchBlock({ force: true });
    await syncDeclarativePornBlock({ force: true });
  }
}

function startPoll() {
  if (gatePollTimer) return;
  gatePollTimer = setInterval(function () {
    void pollGate();
  }, GATE_POLL_MS);
}

extAPI.alarms.create("gate-poll", { periodInMinutes: 1 });
extAPI.alarms.onAlarm.addListener(function (alarm) {
  if (alarm.name === "gate-poll") void pollGate();
});

extAPI.runtime.onInstalled.addListener(function () {
  startPoll();
  void pollGate();
});
extAPI.runtime.onStartup.addListener(function () {
  startPoll();
  void pollGate();
});

startPoll();
void pollGate();

async function softLandBlockedTab(tabId, spaUrl, meta) {
  if (tabId == null || !redirectsEnabled || redirectsPausedByCircuit()) return false;
  meta = meta || {};
  var mode = "";
  var next = "";
  try {
    mode = String((gateCache && gateCache.browser && gateCache.browser.mode) || "").toLowerCase();
    next = String((gateCache && gateCache.morning && gateCache.morning.next) || "").toLowerCase();
  } catch (e) {
    /* ignore */
  }
  var morningSoft =
    next === "bible" || next === "plan" || mode === "bible" || mode === "planning";
  var target = lockedPageUrl();
  if (morningSoft && spaUrl && String(spaUrl).indexOf("locked.html") < 0) {
    target = spaUrl;
  } else if (spaUrl && String(spaUrl).indexOf("locked.html") >= 0) {
    target = spaUrl;
  }
  if (softLandInFlight[tabId] === target) return false;
  var done = softLandDone[tabId];
  if (done && done.target === target && Date.now() - done.at < SOFTLAND_DEDUP_MS) return false;
  try {
    var existing = await extAPI.tabs.get(tabId);
    if (!existing) return false;
    var eu = existing.url ? String(existing.url) : "";
    if (eu.indexOf("locked.html") >= 0) {
      if (!morningSoft || String(target).indexOf("locked.html") >= 0) {
        softLandDone[tabId] = { target: target, at: Date.now() };
        return false;
      }
    }
    if (eu && typeof isCaltSpaUrl === "function" && isCaltSpaUrl(eu) && morningSoft) {
      softLandDone[tabId] = { target: target, at: Date.now() };
      return false;
    }
    if (noteSoftLandAttempt()) return false;
    softLandInFlight[tabId] = target;
    var blockedUrl = meta.fromUrl || eu || "";
    logExtensionEvent("soft_land", {
      kind: meta.kind || "blocked",
      detail: blockedUrl.slice(0, 200),
      url: blockedUrl.slice(0, 400),
      target: target.slice(0, 400),
      tab_id: tabId,
      notify: true,
    });
    showBlockNotification(
      "CALT Gate redirected this tab",
      "Edge was not closed. Blocked: " + (meta.host || blockedUrl.slice(0, 80) || "site")
    );
    await extAPI.tabs.update(tabId, { url: target });
    softLandDone[tabId] = { target: target, at: Date.now() };
    return true;
  } catch (e) {
    return false;
  } finally {
    delete softLandInFlight[tabId];
  }
}

async function maybeRedirectTab(tabId, url, title) {
  if (!redirectsEnabled) return false;
  var gc = gateCacheForBlockCheck();
  if (!gc || (!gc.ok && !gc.degraded)) return false;
  if (!url || (typeof isExtensionOrInternalUrl === "function" && isExtensionOrInternalUrl(url))) return false;
  if (url.indexOf("locked.html") >= 0) return false;
  if (typeof isCaltSpaUrl === "function" && isCaltSpaUrl(url)) return false;

  var host = "";
  try {
    host = typeof hostnameFromUrl === "function" ? hostnameFromUrl(url) : "";
  } catch (e) {
    host = "";
  }
  // Watch / distraction hosts = DNR only — never also softLand (Edge double-hit crash).
  if (host && typeof isForceWatchHost === "function" && isForceWatchHost(host) && watchBlockActive()) {
    return false;
  }
  if (host && typeof isForcePornHost === "function" && isForcePornHost(host)) {
    return false;
  }
  if (!shouldBlockUrl(url, gc, title || "")) return false;
  var browser = gc.browser || {};
  var cat =
    typeof classifyHostCategory === "function"
      ? classifyHostCategory(host, browserPolicyOrFallback(browser))
      : "";
  if (cat === "watch" && watchBlockActive()) return false;

  var kind = typeof blockKindForUrl === "function" ? blockKindForUrl(url, gc, title || "") : "blocked";
  reportGateAlert(kind, url.slice(0, 120));
  var spa = redirectTargetUrl(gc, lockedPageUrlForBlocked(url));
  if (spa && spa.indexOf("locked.html") >= 0) {
    var next = (gc.morning && gc.morning.next) || "";
    var mode = String((gc.browser && gc.browser.mode) || "").toLowerCase();
    if (next === "bible" || mode === "bible") {
      spa = (gc.browser && gc.browser.bible_url) || CALT_BIBLE_URL;
    } else if (next === "plan" || mode === "planning") {
      spa = (gc.browser && gc.browser.plan_url) || CALT_PRODUCTIVITY_URL;
    } else {
      spa = lockedPageUrlForBlocked(url);
    }
  } else if (!spa) {
    spa = lockedPageUrlForBlocked(url);
  }
  return softLandBlockedTab(tabId, spa, { fromUrl: url, kind: kind, host: host });
}

if (extAPI.webNavigation && extAPI.webNavigation.onCommitted) {
  extAPI.webNavigation.onCommitted.addListener(function (details) {
    if (details.frameId !== 0) return;
    if (!details.url || !details.tabId) return;
    void maybeRedirectTab(details.tabId, details.url, "");
  });
}

if (extAPI.tabs && extAPI.tabs.onRemoved) {
  extAPI.tabs.onRemoved.addListener(function (tabId) {
    delete softLandDone[tabId];
    delete softLandInFlight[tabId];
  });
}

function pruneAndLoadTempAllows(cb) {
  extAPI.storage.local.get([TEMP_ALLOW_STORAGE_KEY || "tempAllows"], function (res) {
    var list = Array.isArray(res.tempAllows) ? res.tempAllows : [];
    list = typeof pruneTempAllows === "function" ? pruneTempAllows(list, Date.now()) : list;
    cb(list);
  });
}

extAPI.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
  if (!msg || !msg.type) return false;
  if (msg.type === "CONTENT_SCORE_WARN") {
    return false;
  }
  if (msg.type === "CONTENT_SCORE_LOCK") {
    if (!redirectsEnabled) {
      sendResponse({ ok: false });
      return false;
    }
    var lockUrl = String(msg.url || "");
    var tabId = sender && sender.tab && sender.tab.id;
    reportGateAlert(
      "distraction",
      "content_score:" + String(msg.score || 0) + " " + lockUrl.slice(0, 100)
    );
    if (typeof tabId === "number") {
      void softLandBlockedTab(tabId, lockedPageUrlForBlocked(lockUrl), {
        fromUrl: lockUrl,
        kind: "content_score",
      });
    }
    sendResponse({ ok: true });
    return false;
  }
  if (msg.type === "GET_GATE") {
    sendResponse({ gateCache: gateCache, redirectsEnabled: redirectsEnabled });
    return false;
  }
  if (msg.type === "REFRESH_GATE") {
    void pollGate().then(function () {
      sendResponse({ ok: true, gateCache: gateCache });
    });
    return true;
  }
  if (msg.type === "SET_REDIRECTS") {
    redirectsEnabled = Boolean(msg.enabled);
    extAPI.storage.local.set({ redirectsEnabled: redirectsEnabled });
    void syncDeclarativeWatchBlock({ force: true });
    void syncDeclarativePornBlock({ force: true });
    sendResponse({ ok: true, redirectsEnabled: redirectsEnabled });
    return false;
  }
  if (msg.type === "TEMP_ALLOW_STATUS") {
    var hostS = String(msg.host || "")
      .toLowerCase()
      .replace(/^www\./, "");
    pruneAndLoadTempAllows(function (list) {
      var polS = typeof browserPolicyOrFallback === "function" ? browserPolicyOrFallback(gateCache && gateCache.browser) : {};
      var excludedS = !hostS || (typeof isTempAllowExcludedHost === "function" && isTempAllowExcludedHost(hostS, polS));
      var untilS =
        typeof tempAllowUntilForHost === "function" ? tempAllowUntilForHost(hostS, list, Date.now()) : 0;
      sendResponse({
        ok: true,
        host: hostS,
        excluded: excludedS,
        can_allow: Boolean(hostS) && !excludedS,
        allowed_until: untilS || 0,
        temp_allow_ms: typeof TEMP_ALLOW_MS !== "undefined" ? TEMP_ALLOW_MS : 60000,
        temp_allows: list,
      });
    });
    return true;
  }
  if (msg.type === "TEMP_ALLOW_REQUEST") {
    var hostR = String(msg.host || "")
      .toLowerCase()
      .replace(/^www\./, "");
    var nowR = Date.now();
    var polR = typeof browserPolicyOrFallback === "function" ? browserPolicyOrFallback(gateCache && gateCache.browser) : {};
    var grant = typeof buildTempAllowGrant === "function" ? buildTempAllowGrant(hostR, nowR, polR) : { ok: false };
    if (!grant.ok) {
      sendResponse({
        ok: false,
        error: (grant && grant.error) || "This site can't be temporarily allowed",
        host: hostR,
      });
      return false;
    }
    pruneAndLoadTempAllows(function (list) {
      list = typeof upsertTempAllow === "function" ? upsertTempAllow(list, grant.entry, nowR) : list.concat([grant.entry]);
      tempAllowsCache = list;
      var key = TEMP_ALLOW_STORAGE_KEY || "tempAllows";
      var payload = {};
      payload[key] = list;
      payload.tempAllows = list;
      extAPI.storage.local.set(payload, function () {
        sendResponse({
          ok: true,
          host: grant.entry.host,
          until: grant.entry.until,
          temp_allow_ms: typeof TEMP_ALLOW_MS !== "undefined" ? TEMP_ALLOW_MS : 60000,
        });
      });
    });
    return true;
  }
  return false;
});

// ----- end calt-gate-extension\background.js -----

