# Build Edge MV3 service workers as single files (avoids importScripts NetworkError).
# Run:  powershell -File scripts\build_extension_workers.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot

function Write-Bundle {
  param(
    [string]$OutPath,
    [string[]]$Parts
  )
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("// AUTO-GENERATED by scripts/build_extension_workers.ps1 - do not edit.")
  [void]$sb.AppendLine("// Source parts: $($Parts -join ', ')")
  [void]$sb.AppendLine("")
  foreach ($rel in $Parts) {
    $full = Join-Path $Root $rel
    if (-not (Test-Path $full)) { throw "Missing: $full" }
    [void]$sb.AppendLine("// ----- begin $rel -----")
    [void]$sb.AppendLine((Get-Content -Path $full -Raw -Encoding UTF8))
    [void]$sb.AppendLine("// ----- end $rel -----")
    [void]$sb.AppendLine("")
  }
  $utf8 = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($OutPath, $sb.ToString(), $utf8)
  $len = (Get-Item $OutPath).Length
  Write-Host "Wrote $OutPath ($len bytes)"
}

Write-Bundle -OutPath (Join-Path $Root "selftracker-extension\service_worker.js") -Parts @(
  "selftracker-extension\gate_policy.js",
  "selftracker-extension\telemetry.js",
  "selftracker-extension\background.js"
)

Write-Bundle -OutPath (Join-Path $Root "calt-gate-extension\service_worker.js") -Parts @(
  "calt-gate-extension\gate_policy.js",
  "calt-gate-extension\background.js"
)

Write-Host "Done. In edge://extensions: Remove old copies if needed, Load unpacked, Reload."
